name: Custom Linux Build

on:
  workflow_dispatch:
    inputs:
      build-image-sha:
        type: string
        description: 'SHA for electron/build image'
        default: 'cf814a4d2501e8e843caea071a6b70a48e78b855'
        required: true
  push:
    branches:
      - main
      - '[1-9][0-9]-x-y'
  pull_request:

jobs:
  setup:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    outputs:
        src: ${{ steps.filter.outputs.src }}
        build-image-sha: ${{ steps.set-output.outputs.build-image-sha }}
    steps:
    - uses: actions/custom_checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.0.2
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      with:
        filters: |
          src:
            - '!docs/**'
    - name: Set Outputs for Build Image SHA
      id: set-output
      run: |
        if [ -z "${{ inputs.build-image-sha }}" ]; then
          echo "build-image-sha=cf814a4d2501e8e843caea071a6b70a48e78b855" >> "$GITHUB_OUTPUT"
        else
          echo "build-image-sha=${{ inputs.build-image-sha }}" >> "$GITHUB_OUTPUT"
        fi

  # Checkout Jobs
  checkout-linux:
    needs: setup
    if: ${{ needs.setup.outputs.src == 'true' }}
    runs-on: self-hosted
    container:
      image: ghcr.io/electron/build:${{ needs.setup.outputs.build-image-sha }}
      options: --user root
      volumes:
        - /mnt/cross-instance-cache:/mnt/cross-instance-cache
        - /var/run/sas:/var/run/sas
    env:
      GCLIENT_EXTRA_ARGS: '--custom-var=checkout_arm=True --custom-var=checkout_arm64=True'
    outputs:
      build-image-sha: ${{ needs.setup.outputs.build-image-sha}}
    steps:
    - name: Checkout Electron
      uses: actions/custom_checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        path: src/electron
        fetch-depth: 0
    - name: Checkout & Sync & Save
      uses: ./src/electron/.github/actions/custom_checkout

  # Build Jobs - These cascade into testing jobs
  linux-x64:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: ./.github/workflows/pipeline-electron-build-and-test-and-nan.yml
    needs: checkout-linux
    with:
      build-runs-on: self-hosted
      test-runs-on: self-hosted
      build-container: '{"image":"ghcr.io/electron/build:${{ needs.checkout-linux.outputs.build-image-sha }}","options":"--user root","volumes":["/mnt/cross-instance-cache:/mnt/cross-instance-cache"]}'
      test-container: '{"image":"ghcr.io/electron/build:${{ needs.checkout-linux.outputs.build-image-sha }}","options":"--user root --privileged --init"}'
      target-platform: linux
      target-arch: x64
      is-release: false
      gn-build-type: testing
      generate-symbols: false
      upload-to-storage: '0'
    secrets: inherit
